owner: CodeAny-inc
repo: status
user-agent: computerbox124
sites:
  - name: CodeAny
    url: https://codeany.org
assignees:
  - computerbox124
  - sadykhzadeh
status-website:
  cname: status.codeany.org
  logoUrl: https://cdn.codeany.org/file/codeany-files/static/main/img/codeAnyLogo.svg
  name: Uptime | CodeAny
  introTitle: "**CodeAny** Status Page"
  introMessage: Here you can always check whether CodeAny webpages are up or not.
  navbar:
    - title: Status
      href: /
    - title: CodeAny
      href: https://codeany.org/
    - title: GitHub
      href: https://github.com/$OWNER
